# Generated by Django 3.2.9 on 2021-12-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('time_frame', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('stockname', models.CharField(max_length=120)),
                ('quanty', models.FloatField()),
                ('price', models.FloatField()),
                ('brk', models.FloatField()),
                ('nrate', models.FloatField()),
                ('amt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('buy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_buy_info', to='trading_view.stock_data')),
                ('sell', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_sell_info', to='trading_view.stock_data')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_view.strategy')),
            ],
        ),
    ]
