# Generated by Django 3.2.9 on 2022-09-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
